export const RANKS = [
  // Enlisted
  "PV1", "PV2", "PFC", "SPC", "CPL",
  "SGT", "SSG", "SFC", "MSG", "1SG", "SGM", "CSM", "SMA",
  // Warrant Officers
  "WO1", "CW2", "CW3", "CW4", "CW5",
  // Officers
  "2LT", "1LT", "CPT", "MAJ", "LTC", "COL", "BG", "MG", "LTG", "GEN",
];

export const UNITS = [
  // ── Divisions ──────────────────────────────────────────────────────
  { value: "1AD",    label: "1st Armored Division" },
  { value: "1CD",    label: "1st Cavalry Division" },
  { value: "1ID",    label: "1st Infantry Division" },
  { value: "3ID",    label: "3rd Infantry Division" },
  { value: "4ID",    label: "4th Infantry Division" },
  { value: "7ID",    label: "7th Infantry Division" },
  { value: "10MTN",  label: "10th Mountain Division" },
  { value: "11ABN",  label: "11th Airborne Division" },
  { value: "25ID",   label: "25th Infantry Division" },
  { value: "82ABN",  label: "82nd Airborne Division" },
  { value: "101ABN", label: "101st Airborne Division (Air Assault)" },
  // ── Brigades & Regiments ───────────────────────────────────────────
  { value: "173ABN", label: "173rd Airborne Brigade Combat Team" },
  { value: "75RGR",  label: "75th Ranger Regiment" },
  { value: "160SOAR",label: "160th Special Operations Aviation Regiment" },
  // ── Special Forces Groups ──────────────────────────────────────────
  { value: "1SFG",   label: "1st Special Forces Group (Airborne)" },
  { value: "1SFGD",  label: "1st SFG – Det. 1 (Ft. Lewis / JBLM)" },
  { value: "3SFG",   label: "3rd Special Forces Group (Airborne)" },
  { value: "5SFG",   label: "5th Special Forces Group (Airborne)" },
  { value: "7SFG",   label: "7th Special Forces Group (Airborne)" },
  { value: "10SFG",  label: "10th Special Forces Group (Airborne)" },
  { value: "19SFG",  label: "19th Special Forces Group (Airborne) – ARNG" },
  { value: "20SFG",  label: "20th Special Forces Group (Airborne) – ARNG" },
  // ── Army Major Commands (ACOM) ─────────────────────────────────────
  { value: "FORSCOM",label: "Forces Command (FORSCOM)" },
  { value: "TRADOC", label: "Training & Doctrine Command (TRADOC)" },
  { value: "AMC",    label: "Army Materiel Command (AMC)" },
  { value: "USARPAC",label: "U.S. Army Pacific (USARPAC)" },
  { value: "USAREUR",label: "U.S. Army Europe & Africa (USAREUR-AF)" },
  { value: "ARNORTH",label: "U.S. Army North (ARNORTH / 5th Army)" },
  { value: "ARSOUTH",label: "U.S. Army South (ARSOUTH)" },
  { value: "ARCENTRAL", label: "U.S. Army Central (ARCENT / 3rd Army)" },
  { value: "USARAF", label: "U.S. Army Africa (USARAF)" },
  { value: "USARAK", label: "U.S. Army Alaska (USARAK / 11th Airborne)" },
  { value: "INSCOM", label: "Intelligence & Security Command (INSCOM)" },
  { value: "MEDCOM", label: "Medical Command (MEDCOM)" },
  { value: "USACE",  label: "Corps of Engineers (USACE)" },
  { value: "USACC",  label: "Cadet Command (USACC / ROTC)" },
  { value: "USASOC", label: "Army Special Operations Command (USASOC)" },
  { value: "USACIDC",label: "Criminal Investigation Division (CID)" },
  { value: "USACCSA",label: "Cyber Command (ARCYBER)" },
  { value: "MDW",    label: "Military District of Washington (MDW)" },
  // ── Unified Combatant Commands ─────────────────────────────────────
  { value: "SOCOM",  label: "Special Operations Command (USSOCOM)" },
  { value: "CENTCOM",label: "Central Command (USCENTCOM)" },
  { value: "INDOPACOM", label: "Indo-Pacific Command (USINDOPACOM)" },
  { value: "EUCOM",  label: "European Command (USEUCOM)" },
  { value: "NORTHCOM",  label: "Northern Command (USNORTHCOM)" },
  { value: "SOUTHCOM",  label: "Southern Command (USSOUTHCOM)" },
  { value: "AFRICOM", label: "Africa Command (USAFRICOM)" },
  { value: "CYBERCOM", label: "Cyber Command (USCYBERCOM)" },
  { value: "STRATCOM", label: "Strategic Command (USSTRATCOM)" },
  { value: "TRANSCOM", label: "Transportation Command (USTRANSCOM)" },
  { value: "SPACECOM", label: "Space Command (USSPACECOM)" },
  // ── Components ─────────────────────────────────────────────────────
  { value: "USAR",   label: "U.S. Army Reserve (USAR)" },
  { value: "ARNG",   label: "Army National Guard (ARNG)" },
];

// ── Rank Insignia ─────────────────────────────────────────────────────────────
// Images are bundled locally from public/rank-insignia.
export const RANK_INSIGNIA = {
  "PV1":   null,
  "PV2":   "/rank-insignia/PV2.png",
  "PFC":   "/rank-insignia/PFC.png",
  "SPC":   "/rank-insignia/SPC.png",
  "CPL":   "/rank-insignia/CPL.png",
  "SGT":   "/rank-insignia/SGT.png",
  "SSG":   "/rank-insignia/SSG.png",
  "SFC":   "/rank-insignia/SFC.png",
  "MSG":   "/rank-insignia/MSG.png",
  "1SG":   "/rank-insignia/1SG.png",
  "SGM":   "/rank-insignia/SGM.png",
  "CSM":   "/rank-insignia/CSM.png",
  "SMA":   "/rank-insignia/SMA.png",
  "WO1":   "/rank-insignia/WO1.png",
  "CW2":   "/rank-insignia/CW2.png",
  "CW3":   "/rank-insignia/CW3.png",
  "CW4":   "/rank-insignia/CW4.png",
  "CW5":   "/rank-insignia/CW5.png",
  "2LT":   "/rank-insignia/2LT.png",
  "1LT":   "/rank-insignia/1LT.png",
  "CPT":   "/rank-insignia/CPT.png",
  "MAJ":   "/rank-insignia/MAJ.png",
  "LTC":   "/rank-insignia/LTC.png",
  "COL":   "/rank-insignia/COL.png",
  "BG":    "/rank-insignia/BG.png",
  "MG":    "/rank-insignia/MG.png",
  "LTG":   "/rank-insignia/LTG.png",
  "GEN":   "/rank-insignia/GEN.png",
};

// ── Unit Patches / SSI ────────────────────────────────────────────────────────
// Images are bundled locally from public/unit-patches.
export const UNIT_PATCHES = {
  "1AD":   "/unit-patches/1AD.png",
  "1CD":   "/unit-patches/1CD.png",
  "1ID":   "/unit-patches/1ID.png",
  "3ID":   "/unit-patches/3ID.png",
  "4ID":   "/unit-patches/4ID.png",
  "7ID":   "/unit-patches/7ID.png",
  "10MTN": "/unit-patches/10MTN.png",
  "11ABN": "/unit-patches/11ABN.png",
  "25ID":  "/unit-patches/25ID.png",
  "82ABN": "/unit-patches/82ABN.png",
  "101ABN": "/unit-patches/101ABN.jpg",
  "173ABN": "/unit-patches/173ABN.png",
  "75RGR": "/unit-patches/75RGR.png",
  "160SOAR": "/unit-patches/160SOAR.svg",
  "1SFG":  "/unit-patches/1SFG.png",
  "1SFGD": "/unit-patches/1SFGD.png",
  "3SFG":  "/unit-patches/3SFG.png",
  "5SFG":  "/unit-patches/5SFG.png",
  "7SFG":  "/unit-patches/7SFG.png",
  "10SFG": "/unit-patches/10SFG.png",
  "19SFG": "/unit-patches/19SFG.png",
  "20SFG": "/unit-patches/20SFG.png",
  "FORSCOM": "/unit-patches/FORSCOM.png",
  "TRADOC": "/unit-patches/TRADOC.png",
  "AMC":   "/unit-patches/AMC.png",
  "USARPAC": "/unit-patches/USARPAC.png",
  "USAREUR": "/unit-patches/USAREUR.png",
  "ARNORTH": "/unit-patches/ARNORTH.png",
  "ARSOUTH": "/unit-patches/ARSOUTH.png",
  "ARCENTRAL": "/unit-patches/ARCENTRAL.png",
  "USARAF": "/unit-patches/USARAF.png",
  "USARAK": "/unit-patches/USARAK.png",
  "INSCOM": "/unit-patches/INSCOM.jpg",
  "MEDCOM": "/unit-patches/MEDCOM.png",
  "USACE": "/unit-patches/USACE.gif",
  "USACC": "/unit-patches/USACC.png",
  "USASOC": "/unit-patches/USASOC.png",
  "USACIDC": "/unit-patches/USACIDC.png",
  "USACCSA": "/unit-patches/USACCSA.png",
  "MDW":   "/unit-patches/MDW.png",
  "SOCOM": "/unit-patches/SOCOM.png",
  "CENTCOM": "/unit-patches/CENTCOM.png",
  "INDOPACOM": "/unit-patches/INDOPACOM.png",
  "EUCOM": "/unit-patches/EUCOM.png",
  "NORTHCOM": "/unit-patches/NORTHCOM.png",
  "SOUTHCOM": "/unit-patches/SOUTHCOM.png",
  "AFRICOM": "/unit-patches/AFRICOM.png",
  "CYBERCOM": "/unit-patches/CYBERCOM.png",
  "STRATCOM": null,
  "TRANSCOM": null,
  "SPACECOM": null,
  "USAR":  "/unit-patches/USAR.png",
  "ARNG":  "/unit-patches/ARNG.png",
};