// Unit list aligned with Wikipedia current Army formations:
// https://en.wikipedia.org/wiki/List_of_current_formations_of_the_United_States_Army
// Patches: public/unit-patches (sync: npm run sync-patches)

export const RANKS = [
  // Enlisted
  "PV1", "PV2", "PFC", "SPC", "CPL",
  "SGT", "SSG", "SFC", "MSG", "1SG", "SGM", "CSM", "SMA",
  // Warrant Officers
  "WO1", "CW2", "CW3", "CW4", "CW5",
  // Officers
  "2LT", "1LT", "CPT", "MAJ", "LTC", "COL", "BG", "MG", "LTG", "GEN",
];





export const UNITS = [
  // ── Field Armies ──────────────────────────────────────────
  { value: "1A", label: "First United States Army" },
  { value: "3A", label: "Third United States Army" },
  { value: "5A", label: "Fifth United States Army" },
  { value: "6A", label: "Sixth United States Army" },
  { value: "8A", label: "Eighth United States Army" },
  // ── Corps ─────────────────────────────────────────────────
  { value: "ICORPS", label: "I Corps" },
  { value: "IIICORPS", label: "III Armored Corps" },
  { value: "VCORPS", label: "V Corps" },
  { value: "XVIIIABN", label: "XVIII Airborne Corps" },
  // ── Airborne Divisions ────────────────────────────────────
  { value: "11ABN", label: "11th Airborne Division" },
  { value: "82ABN", label: "82nd Airborne Division" },
  { value: "101ABN", label: "101st Airborne Division (Air Assault)" },
  // ── Armored Divisions ─────────────────────────────────────
  { value: "1AD", label: "1st Armored Division" },
  { value: "1CD", label: "1st Cavalry Division" },
  // ── Infantry Divisions (Active) ───────────────────────────
  { value: "1ID", label: "1st Infantry Division" },
  { value: "2ID", label: "2nd Infantry Division" },
  { value: "3ID", label: "3rd Infantry Division" },
  { value: "4ID", label: "4th Infantry Division" },
  { value: "7ID", label: "7th Infantry Division" },
  { value: "10MTN", label: "10th Mountain Division" },
  { value: "25ID", label: "25th Infantry Division" },
  // ── Infantry Divisions (ARNG) ─────────────────────────────
  { value: "28ID", label: "28th Infantry Division (ARNG)" },
  { value: "29ID", label: "29th Infantry Division (ARNG)" },
  { value: "34ID", label: "34th Infantry Division (ARNG)" },
  { value: "35ID", label: "35th Infantry Division (ARNG)" },
  { value: "36ID", label: "36th Infantry Division (ARNG)" },
  { value: "38ID", label: "38th Infantry Division (ARNG)" },
  { value: "40ID", label: "40th Infantry Division (ARNG)" },
  { value: "42ID", label: "42nd Infantry Division (ARNG)" },
  // ── Training Divisions (USAR) ─────────────────────────────
  { value: "78TD", label: "78th Training Division (USAR)" },
  { value: "86TD", label: "86th Training Division (USAR)" },
  { value: "87TD", label: "87th Training Division (USAR)" },
  { value: "91DIV", label: "91st Division (USAR)" },
  { value: "94DIV", label: "94th Division (USAR)" },
  { value: "95DIV", label: "95th Division (USAR)" },
  { value: "98TD", label: "98th Training Division (USAR)" },
  { value: "100TD", label: "100th Division (USAR)" },
  { value: "102DIV", label: "102nd Division (USAR)" },
  { value: "104DIV", label: "104th Division (USAR)" },
  // ── Readiness Divisions (USAR) ────────────────────────────
  { value: "88RD", label: "88th Readiness Division (USAR)" },
  // ── Airborne Brigades ─────────────────────────────────────
  { value: "173ABN", label: "173rd Airborne Brigade Combat Team" },
  // ── Air Defense Artillery Brigades ────────────────────────
  { value: "11ADA", label: "11th Air Defense Artillery Brigade" },
  { value: "31ADA", label: "31st Air Defense Artillery Brigade" },
  { value: "35ADA", label: "35th Air Defense Artillery Brigade" },
  { value: "38ADA", label: "38th Air Defense Artillery Brigade" },
  { value: "69ADA", label: "69th Air Defense Artillery Brigade" },
  { value: "100MD", label: "100th Missile Defense Brigade (ARNG)" },
  { value: "108ADA", label: "108th Air Defense Artillery Brigade" },
  { value: "164ADA", label: "164th Air Defense Artillery Brigade (ARNG)" },
  { value: "174ADA", label: "174th Air Defense Artillery Brigade (ARNG)" },
  { value: "678ADA", label: "678th Air Defense Artillery Brigade (ARNG)" },
  // ── Armored Brigades ──────────────────────────────────────
  { value: "5AB", label: "5th Armored Brigade (USAR)" },
  { value: "30ABCT", label: "30th Armored Brigade Combat Team (ARNG)" },
  { value: "81SBCT", label: "81st Stryker Brigade Combat Team (ARNG)" },
  { value: "155ABCT", label: "155th Armored Brigade Combat Team (ARNG)" },
  { value: "177AB", label: "177th Armored Brigade (USAR)" },
  { value: "194AB", label: "194th Armored Brigade" },
  // ── Aviation Brigades ─────────────────────────────────────
  { value: "1AVN", label: "1st Aviation Brigade" },
  { value: "11ECAB", label: "11th Expeditionary Combat Aviation Brigade (USAR)" },
  { value: "12CAB", label: "12th Combat Aviation Brigade" },
  { value: "16CAB", label: "16th Combat Aviation Brigade" },
  { value: "29CAB", label: "29th Combat Aviation Brigade (ARNG)" },
  { value: "63TAB", label: "63rd Theater Aviation Brigade (ARNG)" },
  { value: "77CAB", label: "77th Combat Aviation Brigade (ARNG)" },
  { value: "110AVN", label: "110th Aviation Brigade" },
  { value: "128AVN", label: "128th Aviation Brigade" },
  { value: "166AVN", label: "166th Aviation Brigade (USAR)" },
  { value: "185CAB", label: "185th Aviation Brigade (ARNG)" },
  { value: "244ECAB", label: "244th Expeditionary Combat Aviation Brigade (USAR)" },
  // ── Military Intelligence Brigades ────────────────────────
  { value: "201EMIB", label: "201st Expeditionary Military Intelligence Brigade" },
  { value: "504EMIB", label: "504th Expeditionary Military Intelligence Brigade" },
  { value: "525EMIB", label: "525th Expeditionary Military Intelligence Brigade" },
  // ── Engineer Brigades ─────────────────────────────────────
  { value: "20EN", label: "20th Engineer Brigade" },
  { value: "36EN", label: "36th Engineer Brigade" },
  { value: "130EN", label: "130th Engineer Brigade" },
  { value: "555EN", label: "555th Engineer Brigade" },
  { value: "7EN", label: "7th Engineer Brigade" },
  // ── Field Artillery Brigades ──────────────────────────────
  { value: "17FA", label: "17th Field Artillery Brigade" },
  { value: "18FA", label: "18th Field Artillery Brigade" },
  { value: "75FA", label: "75th Field Artillery Brigade" },
  { value: "210FA", label: "210th Field Artillery Brigade" },
  // ── Special Forces Groups ─────────────────────────────────
  { value: "1SFG", label: "1st Special Forces Group (Airborne)" },
  { value: "1SFGD", label: "1st SFG – Det. 1 (JBLM)" },
  { value: "3SFG", label: "3rd Special Forces Group (Airborne)" },
  { value: "5SFG", label: "5th Special Forces Group (Airborne)" },
  { value: "7SFG", label: "7th Special Forces Group (Airborne)" },
  { value: "10SFG", label: "10th Special Forces Group (Airborne)" },
  { value: "19SFG", label: "19th Special Forces Group (Airborne) – ARNG" },
  { value: "20SFG", label: "20th Special Forces Group (Airborne) – ARNG" },
  // ── Information Operations Groups ─────────────────────────
  { value: "56TIOG", label: "56th Theater Information Operations Group (ARNG)" },
  { value: "71TIOG", label: "71st Theater Information Operations Group (ARNG)" },
  { value: "151TIOG", label: "151st Theater Information Operations Group (USAR)" },
  // ── Independent Regiments ─────────────────────────────────
  { value: "2CR", label: "2nd Cavalry Regiment" },
  { value: "3CR", label: "3rd Cavalry Regiment" },
  { value: "3INF", label: "3rd Infantry Regiment (The Old Guard)" },
  { value: "11ACR", label: "11th Armored Cavalry Regiment" },
  { value: "278ACR", label: "278th Armored Cavalry Regiment (ARNG)" },
  { value: "75RGR", label: "75th Ranger Regiment" },
  { value: "160SOAR", label: "160th Special Operations Aviation Regiment" },
  // ── Army Major Commands ───────────────────────────────────
  { value: "FORSCOM", label: "Forces Command (FORSCOM)" },
  { value: "TRADOC", label: "Training & Doctrine Command (TRADOC)" },
  { value: "AMC", label: "Army Materiel Command (AMC)" },
  { value: "USARPAC", label: "U.S. Army Pacific (USARPAC)" },
  { value: "USAREUR", label: "U.S. Army Europe & Africa (USAREUR-AF)" },
  { value: "ARNORTH", label: "U.S. Army North (ARNORTH)" },
  { value: "ARSOUTH", label: "U.S. Army South (ARSOUTH)" },
  { value: "ARCENTRAL", label: "U.S. Army Central (ARCENT)" },
  { value: "USARAF", label: "U.S. Army Africa (USARAF)" },
  { value: "USARAK", label: "U.S. Army Alaska (USARAK)" },
  { value: "INSCOM", label: "Intelligence & Security Command (INSCOM)" },
  { value: "MEDCOM", label: "Medical Command (MEDCOM)" },
  { value: "USACE", label: "Corps of Engineers (USACE)" },
  { value: "USACC", label: "Cadet Command (USACC / ROTC)" },
  { value: "USASOC", label: "Army Special Operations Command (USASOC)" },
  { value: "USACIDC", label: "Criminal Investigation Division (CID)" },
  { value: "USACCSA", label: "Cyber Command (ARCYBER)" },
  { value: "MDW", label: "Military District of Washington (MDW)" },
  // ── Unified Combatant Commands ────────────────────────────
  { value: "SOCOM", label: "Special Operations Command (USSOCOM)" },
  { value: "CENTCOM", label: "Central Command (USCENTCOM)" },
  { value: "INDOPACOM", label: "Indo-Pacific Command (USINDOPACOM)" },
  { value: "EUCOM", label: "European Command (USEUCOM)" },
  { value: "NORTHCOM", label: "Northern Command (USNORTHCOM)" },
  { value: "SOUTHCOM", label: "Southern Command (USSOUTHCOM)" },
  { value: "AFRICOM", label: "Africa Command (USAFRICOM)" },
  { value: "CYBERCOM", label: "Cyber Command (USCYBERCOM)" },
  { value: "STRATCOM", label: "Strategic Command (USSTRATCOM)" },
  { value: "TRANSCOM", label: "Transportation Command (USTRANSCOM)" },
  { value: "SPACECOM", label: "Space Command (USSPACECOM)" },
  // ── Components ────────────────────────────────────────────
  { value: "USAR", label: "U.S. Army Reserve (USAR)" },
  { value: "ARNG", label: "Army National Guard (ARNG)" },
];

// ── Rank Insignia ─────────────────────────────────────────────────────────────
// Images are bundled locally from public/rank-insignia.
export const RANK_INSIGNIA = {
  "PV1":   null,
  "PV2":   "/rank-insignia/PV2.png",
  "PFC":   "/rank-insignia/PFC.png",
  "SPC":   "/rank-insignia/SPC.png",
  "CPL":   "/rank-insignia/CPL.png",
  "SGT":   "/rank-insignia/SGT.png",
  "SSG":   "/rank-insignia/SSG.png",
  "SFC":   "/rank-insignia/SFC.png",
  "MSG":   "/rank-insignia/MSG.png",
  "1SG":   "/rank-insignia/1SG.png",
  "SGM":   "/rank-insignia/SGM.png",
  "CSM":   "/rank-insignia/CSM.png",
  "SMA":   "/rank-insignia/SMA.png",
  "WO1":   "/rank-insignia/WO1.png",
  "CW2":   "/rank-insignia/CW2.png",
  "CW3":   "/rank-insignia/CW3.png",
  "CW4":   "/rank-insignia/CW4.png",
  "CW5":   "/rank-insignia/CW5.png",
  "2LT":   "/rank-insignia/2LT.png",
  "1LT":   "/rank-insignia/1LT.png",
  "CPT":   "/rank-insignia/CPT.png",
  "MAJ":   "/rank-insignia/MAJ.png",
  "LTC":   "/rank-insignia/LTC.png",
  "COL":   "/rank-insignia/COL.png",
  "BG":    "/rank-insignia/BG.png",
  "MG":    "/rank-insignia/MG.png",
  "LTG":   "/rank-insignia/LTG.png",
  "GEN":   "/rank-insignia/GEN.png",
};

// ── Unit Patches / SSI ────────────────────────────────────────────────────────
// Images are bundled locally from public/unit-patches.
export const UNIT_PATCHES = {
  "1A":        "/unit-patches/1A.png",
  "3A":        "/unit-patches/3A.png",
  "5A":        "/unit-patches/5A.png",
  "6A":        "/unit-patches/6A.png",
  "8A":        "/unit-patches/8A.png",
  "ICORPS":    "/unit-patches/ICORPS.png",
  "IIICORPS":  "/unit-patches/IIICORPS.png",
  "VCORPS":    "/unit-patches/VCORPS.png",
  "XVIIIABN":  "/unit-patches/XVIIIABN.png",
  "11ABN":     "/unit-patches/11ABN.png",
  "82ABN":     "/unit-patches/82ABN.png",
  "101ABN":    "/unit-patches/101ABN.png",
  "1AD":       "/unit-patches/1AD.png",
  "1CD":       "/unit-patches/1CD.png",
  "1ID":       "/unit-patches/1ID.png",
  "2ID":       "/unit-patches/2ID.png",
  "3ID":       "/unit-patches/3ID.png",
  "4ID":       "/unit-patches/4ID.png",
  "7ID":       "/unit-patches/7ID.png",
  "10MTN":     "/unit-patches/10MTN.png",
  "25ID":      "/unit-patches/25ID.png",
  "28ID":      "/unit-patches/28ID.png",
  "29ID":      "/unit-patches/29ID.png",
  "34ID":      "/unit-patches/34ID.png",
  "35ID":      "/unit-patches/35ID.png",
  "36ID":      "/unit-patches/36ID.png",
  "38ID":      "/unit-patches/38ID.png",
  "40ID":      "/unit-patches/40ID.png",
  "42ID":      "/unit-patches/42ID.png",
  "78TD":      "/unit-patches/78TD.png",
  "86TD":      "/unit-patches/86TD.png",
  "87TD":      "/unit-patches/87TD.png",
  "91DIV":     "/unit-patches/91DIV.png",
  "94DIV":     "/unit-patches/94DIV.png",
  "95DIV":     "/unit-patches/95DIV.png",
  "98TD":      "/unit-patches/98TD.png",
  "100TD":     "/unit-patches/100TD.png",
  "102DIV":    "/unit-patches/102DIV.png",
  "104DIV":    "/unit-patches/104DIV.png",
  "88RD":      "/unit-patches/88RD.png",
  "173ABN":    "/unit-patches/173ABN.png",
  "11ADA":     "/unit-patches/11ADA.png",
  "31ADA":     "/unit-patches/31ADA.png",
  "35ADA":     "/unit-patches/35ADA.png",
  "38ADA":     "/unit-patches/38ADA.png",
  "69ADA":     "/unit-patches/69ADA.png",
  "100MD":     "/unit-patches/100MD.png",
  "108ADA":    "/unit-patches/108ADA.png",
  "164ADA":    "/unit-patches/164ADA.png",
  "174ADA":    "/unit-patches/174ADA.png",
  "678ADA":    "/unit-patches/678ADA.png",
  "5AB":       "/unit-patches/5AB.png",
  "30ABCT":    "/unit-patches/30ABCT.png",
  "81SBCT":    "/unit-patches/81SBCT.png",
  "155ABCT":   "/unit-patches/155ABCT.png",
  "177AB":     "/unit-patches/177AB.png",
  "194AB":     "/unit-patches/194AB.png",
  "1AVN":      "/unit-patches/1AVN.png",
  "11ECAB":    "/unit-patches/11ECAB.png",
  "12CAB":     "/unit-patches/12CAB.png",
  "16CAB":     "/unit-patches/16CAB.png",
  "29CAB":     "/unit-patches/29CAB.png",
  "63TAB":     "/unit-patches/63TAB.png",
  "77CAB":     "/unit-patches/77CAB.png",
  "110AVN":    "/unit-patches/110AVN.png",
  "128AVN":    "/unit-patches/128AVN.png",
  "166AVN":    "/unit-patches/166AVN.png",
  "185CAB":    "/unit-patches/185CAB.png",
  "244ECAB":   "/unit-patches/244ECAB.png",
  "201EMIB":   "/unit-patches/201EMIB.png",
  "504EMIB":   "/unit-patches/504EMIB.png",
  "525EMIB":   "/unit-patches/525EMIB.png",
  "20EN":      "/unit-patches/20EN.png",
  "36EN":      "/unit-patches/36EN.png",
  "130EN":     "/unit-patches/130EN.png",
  "555EN":     "/unit-patches/555EN.png",
  "7EN":       "/unit-patches/7EN.png",
  "17FA":      null,
  "18FA":      "/unit-patches/18FA.png",
  "75FA":      "/unit-patches/75FA.png",
  "210FA":     "/unit-patches/210FA.png",
  "1SFG":      "/unit-patches/1SFG.png",
  "1SFGD":     "/unit-patches/1SFGD.png",
  "3SFG":      "/unit-patches/3SFG.png",
  "5SFG":      "/unit-patches/5SFG.png",
  "7SFG":      "/unit-patches/7SFG.png",
  "10SFG":     "/unit-patches/10SFG.png",
  "19SFG":     "/unit-patches/19SFG.png",
  "20SFG":     "/unit-patches/20SFG.png",
  "56TIOG":    "/unit-patches/56TIOG.png",
  "71TIOG":    null,
  "151TIOG":   "/unit-patches/151TIOG.png",
  "2CR":       "/unit-patches/2CR.png",
  "3CR":       "/unit-patches/3CR.png",
  "3INF":      "/unit-patches/3INF.png",
  "11ACR":     "/unit-patches/11ACR.png",
  "278ACR":    "/unit-patches/278ACR.png",
  "75RGR":     "/unit-patches/75RGR.png",
  "160SOAR":   "/unit-patches/160SOAR.png",
  "FORSCOM":   "/unit-patches/FORSCOM.png",
  "TRADOC":    "/unit-patches/TRADOC.png",
  "AMC":       "/unit-patches/AMC.png",
  "USARPAC":   "/unit-patches/USARPAC.png",
  "USAREUR":   "/unit-patches/USAREUR.png",
  "ARNORTH":   "/unit-patches/ARNORTH.png",
  "ARSOUTH":   "/unit-patches/ARSOUTH.png",
  "ARCENTRAL": "/unit-patches/ARCENTRAL.png",
  "USARAF":    "/unit-patches/USARAF.png",
  "USARAK":    "/unit-patches/USARAK.png",
  "INSCOM":    "/unit-patches/INSCOM.png",
  "MEDCOM":    "/unit-patches/MEDCOM.png",
  "USACE":     "/unit-patches/USACE.png",
  "USACC":     "/unit-patches/USACC.png",
  "USASOC":    "/unit-patches/USASOC.png",
  "USACIDC":   "/unit-patches/USACIDC.png",
  "USACCSA":   "/unit-patches/USACCSA.png",
  "MDW":       "/unit-patches/MDW.png",
  "SOCOM":     "/unit-patches/SOCOM.png",
  "CENTCOM":   "/unit-patches/CENTCOM.png",
  "INDOPACOM": "/unit-patches/INDOPACOM.png",
  "EUCOM":     "/unit-patches/EUCOM.png",
  "NORTHCOM":  "/unit-patches/NORTHCOM.png",
  "SOUTHCOM":  "/unit-patches/SOUTHCOM.png",
  "AFRICOM":   "/unit-patches/AFRICOM.png",
  "CYBERCOM":  "/unit-patches/CYBERCOM.png",
  "STRATCOM":  null,
  "TRANSCOM":  null,
  "SPACECOM":  null,
  "USAR":      "/unit-patches/USAR.png",
  "ARNG":      "/unit-patches/ARNG.png",
};

